version: "3.9"
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      test:  [ "CMD", "rabbitmqctl", "status"]
      interval: 1s
      timeout: 30s
      retries: 30
    networks:
      - pathfinder

  pathfinder:
    build:
      context: pathfinder/.
      dockerfile: Dockerfile
    container_name: pathfinder
    depends_on:
      rabbitmq:
        condition: service_healthy
    hostname: pathfinder
    environment:
      PATHFINDER_RABBIT_HOST: rabbitmq
      PATHFINDER_RABBIT_PORT: 5672
      PATHFINDER_RABBIT_USER: guest
      PATHFINDER_RABBIT_PASSWORD: guest
      PATHFINDER_RABBIT_VHOST: /
      PATHFINDER_RABBIT_LISTENER_PROBLEMS_QUEUE: cb.RoutingProblems.Problems
    networks:
      - pathfinder

  mockdelivery:
    build:
      context: mockdelivery/.
      dockerfile: Dockerfile
    container_name: mockdelivery
    depends_on:
      rabbitmq:
        condition: service_healthy
    hostname: mockdelivery
    environment:
      MOCKDELIVERY_RABBIT_HOST: rabbitmq
      MOCKDELIVERY_RABBIT_PORT: 5672
      MOCKDELIVERY_RABBIT_USER: guest
      MOCKDELIVERY_RABBIT_PASSWORD: guest
      MOCKDELIVERY_RABBIT_VHOST: /
      MOCKDELIVERY_PROBLEM_QUEUE: cb.RoutingProblems.Problems
    networks:
      - pathfinder

networks:
  pathfinder:
    driver: bridge